spring:

  application:
    name:DocumentsWenKu
  # Datasource
  datasource:
    url: jdbc:mysql://43.136.173.33:3306/wenku_user
    username: "gaffey"
    password: syj4527466
    driver-class-name: com.mysql.cj.jdbc.Driver
#  Redis
  redis:
    host: 1.14.1.82
    port: 6379
    password: 4527466
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    timeout: 3000
    database: 0


# Mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)

ftp:
  hostname: 1.14.1.82
  port: 21
  username: ftpuser
  password: syj4527466
logging:
  file:
    name: Wenku_log.log
